### ISSUE TITLE
[DISCUSS] Method of #![deny(current_warnings)]

### ISSUE THREAD

**Issue by CAD97** [crate-ci/example-warn#1]
I find this tower annoying:

https://github.com/crate-ci/example-warn/blob/5cbaf772c6d3a1b74f29bd86d63e5970453ea48e/src/lib.rs#L1-L36

Reasoning:

- 36 (and more in the future) lines of code in the root before the interesting part
- This prevents local compilation from continuing after a warning
  - Depending on the warning, it can be detected before real errors and prevent them from showing
  - Often times when iterating I care more about correctness than eliminating warnings _right now_
  - It's beneficial to the compiler UI to have a visual separation between warnings and errors

I fully agree that warnings should be treated as errors _on CI_. So how do we get `cargo build` to treat warnings as errors? By the [`RUSTFLAGS` environment variable](https://doc.rust-lang.org/cargo/reference/environment-variables.html)!

With `RUSTFLAGS=-D warnings` you can deny the warning group `warnings`. (For the same reason that we don't use `!#[deny(warnings)]`, this is dangerous. Though we're still technically not free from warnings introduced by new versions of the compiler; deprecation of symbols can introduce deprecation warnings. (As such that one should probably be excluded from our exclusion list.)) With `RUSTFLAGS=-D const_err -D dead_code ...` you can specify warning (groups) individually.

**Comment by epage** [comment]
I personally exclusively develop with warnings on :)

An alternative method for allowing both is a `dev` feature (documented in the book).  So some of my contributors do this:
```
cargo test --features "dev"
```

**Comment by epage** [comment]
As you mention, with `RUSTFLAGS`, we're trading a tower in each of our top-level `.rs` files with a tower in each of our CI files ... and not a good way for our users to run it.

I'm going to be writing up an RFC for warning groups to be split in two, normal and `-unstable`.  The normal ones do not change on epoch boundaries.

See https://github.com/rust-lang/rust/issues/44581#issuecomment-366006235

**Comment by epage** [comment]
In preparing for writing my RFC, I've been giving this more thought, including workarounds and alternative approaches.

One alternative is to do:
```yml
matrix:
  include:
  - rust: 1.24.0  # Locking down for consistent behavior
    env: RUSTFLAGS=-D warnings
    install:
    script:
    - cargo check --tests
```

Pros
- Does not break with time
- Does not get in the way of rapid iteration when prototyping ideas
- Easy to manually enable (though might be stricter if the user is on a different compiler version)
- Less copy / paste of large warning groups
- No RFC process / wait :)
- Easily [customize targets](https://github.com/rust-lang/cargo/pull/4592) or warnings (I'm assuming you can do `-D warnings -A dead-code` to subtract checks)

Cons
- Manual updating of rust version (also done for rustfmt)
- Enforcement is delayed until the PR
- User won't know about `allow`ed warnings until their PR
  - We could `#![warn(warnings)]` but I assume that will lower all `deny`s to `warn` and I doubt we want that.

Thoughts?

**Comment by CAD97** [comment]
A generic `#![warn(warnings)]` does not override a `#[deny]` by default: [[play](https://play.rust-lang.org/?gist=961afe392a8e9161d6bb49f963d67bcf)]. A crate noting that they deny warnings in CONTRIBUTING would be enough to inform contributors to address or `#[allow]` warnings in their contributions.

Pinning to a compiler version has the benefit of also eliminating problems with other forms of warning creep. Bumping CI requirements should be done in the repository history along with necessary fixes for the bumped requirements (if as simple as `#[allow]`s, otherwise they're actual improvements which could be landed separately). The only problem I see is potential for false positives in the pinned version, which is [uncommon but happens](https://github.com/rust-lang/rust/issues?q=is%3Aissue+false+positive+label%3AA-lint) (link includes many non-false-positive reports but I couldn't do better).

**Comment by epage** [comment]
I also decided to ping "users" about it before I wrote up an RFC

https://users.rust-lang.org/t/handling-warnings-in-a-ci/15669

Even if the RFC happens, it'll probably be worthwhile to switch to the pinned compiler until stable groups are available.
